#!/usr/bin/env bash

set -euo pipefail

if [[ -d /var/lib/docker ]]; then
  setfacl -R -m d:u:alloy:rx /var/lib/docker
  setfacl -R -m u:alloy:rx /var/lib/docker
fi

if [[ -S /run/containerd/containerd.sock ]]; then
  setfacl -m u:alloy:rw /run/containerd/containerd.sock
fi

systemctl restart alloy.service
