BEGIN;

CREATE TABLE IF NOT EXISTS public.workspaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    slug VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    repo_full_name VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT workspaces_owner_id_fkey
        FOREIGN KEY (owner_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT workspaces_owner_slug_key
        UNIQUE (owner_id, slug)
);

CREATE INDEX IF NOT EXISTS workspaces_owner_id_idx
    ON public.workspaces (owner_id);

INSERT INTO public.workspaces (owner_id, slug, name, created_at, updated_at)
SELECT
    id,
    'default',
    COALESCE(NULLIF(nickname, ''), NULLIF(username, ''), 'My Workspace'),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM public.users
ON CONFLICT (owner_id, slug) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    content TEXT,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tasks_workspace_id_fkey
        FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE,
    CONSTRAINT tasks_author_id_fkey
        FOREIGN KEY (author_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT tasks_status_check
        CHECK (status IN ('TODO', 'DOING', 'DONE'))
);

CREATE INDEX IF NOT EXISTS tasks_workspace_id_idx
    ON public.tasks (workspace_id);

CREATE INDEX IF NOT EXISTS tasks_author_id_idx
    ON public.tasks (author_id);

CREATE TABLE IF NOT EXISTS public.logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    task_id BIGINT,
    kind VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'NONE',
    title VARCHAR(255) NOT NULL,
    summary TEXT,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP,
    CONSTRAINT logs_workspace_id_fkey
        FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE,
    CONSTRAINT logs_author_id_fkey
        FOREIGN KEY (author_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT logs_task_id_fkey
        FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE SET NULL,
    CONSTRAINT logs_kind_check
        CHECK (kind IN ('ISSUE', 'FIX', 'DECISION', 'NOTE')),
    CONSTRAINT logs_status_check
        CHECK (status IN ('NONE', 'OPEN', 'CLOSED')),
    CONSTRAINT logs_kind_status_check
        CHECK (
            (kind = 'ISSUE' AND status IN ('OPEN', 'CLOSED'))
            OR (kind <> 'ISSUE' AND status = 'NONE')
        )
);

CREATE INDEX IF NOT EXISTS logs_workspace_id_idx
    ON public.logs (workspace_id);

CREATE INDEX IF NOT EXISTS logs_author_id_idx
    ON public.logs (author_id);

CREATE INDEX IF NOT EXISTS logs_task_id_idx
    ON public.logs (task_id);

CREATE INDEX IF NOT EXISTS logs_open_issues_idx
    ON public.logs (workspace_id, status)
    WHERE kind = 'ISSUE';

CREATE TABLE IF NOT EXISTS public.log_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_log_id BIGINT NOT NULL,
    to_log_id BIGINT NOT NULL,
    relation VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT log_links_from_log_id_fkey
        FOREIGN KEY (from_log_id) REFERENCES public.logs(id) ON DELETE CASCADE,
    CONSTRAINT log_links_to_log_id_fkey
        FOREIGN KEY (to_log_id) REFERENCES public.logs(id) ON DELETE CASCADE,
    CONSTRAINT log_links_no_self_link
        CHECK (from_log_id <> to_log_id),
    CONSTRAINT log_links_relation_check
        CHECK (relation IN ('FIXES', 'RELATES_TO', 'SUPERSEDES')),
    CONSTRAINT log_links_from_to_relation_key
        UNIQUE (from_log_id, to_log_id, relation)
);

CREATE INDEX IF NOT EXISTS log_links_from_log_id_idx
    ON public.log_links (from_log_id);

CREATE INDEX IF NOT EXISTS log_links_to_log_id_idx
    ON public.log_links (to_log_id);

CREATE TABLE IF NOT EXISTS public.todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    task_id BIGINT,
    origin_log_id BIGINT,
    title VARCHAR(255) NOT NULL,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    planned_for DATE NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    CONSTRAINT todos_workspace_id_fkey
        FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE,
    CONSTRAINT todos_author_id_fkey
        FOREIGN KEY (author_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT todos_task_id_fkey
        FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE SET NULL,
    CONSTRAINT todos_origin_log_id_fkey
        FOREIGN KEY (origin_log_id) REFERENCES public.logs(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS todos_workspace_planned_for_idx
    ON public.todos (workspace_id, planned_for, sort_order);

CREATE INDEX IF NOT EXISTS todos_author_id_idx
    ON public.todos (author_id);

CREATE INDEX IF NOT EXISTS todos_task_id_idx
    ON public.todos (task_id);

CREATE INDEX IF NOT EXISTS todos_origin_log_id_idx
    ON public.todos (origin_log_id);

CREATE TABLE IF NOT EXISTS public.outputs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP,
    CONSTRAINT outputs_workspace_id_fkey
        FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE,
    CONSTRAINT outputs_author_id_fkey
        FOREIGN KEY (author_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT outputs_type_check
        CHECK (type IN ('POST_DRAFT', 'PR_DOC', 'RELEASE_NOTE', 'WEEKLY_RECAP')),
    CONSTRAINT outputs_status_check
        CHECK (status IN ('DRAFT', 'EXPORTED', 'PUBLISHED', 'ARCHIVED'))
);

CREATE INDEX IF NOT EXISTS outputs_workspace_status_idx
    ON public.outputs (workspace_id, status);

CREATE INDEX IF NOT EXISTS outputs_author_id_idx
    ON public.outputs (author_id);

CREATE TABLE IF NOT EXISTS public.output_logs (
    output_id BIGINT NOT NULL,
    log_id BIGINT NOT NULL,
    CONSTRAINT output_logs_pkey PRIMARY KEY (output_id, log_id),
    CONSTRAINT output_logs_output_id_fkey
        FOREIGN KEY (output_id) REFERENCES public.outputs(id) ON DELETE CASCADE,
    CONSTRAINT output_logs_log_id_fkey
        FOREIGN KEY (log_id) REFERENCES public.logs(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS output_logs_log_id_idx
    ON public.output_logs (log_id);

CREATE TABLE IF NOT EXISTS public.output_tasks (
    output_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    CONSTRAINT output_tasks_pkey PRIMARY KEY (output_id, task_id),
    CONSTRAINT output_tasks_output_id_fkey
        FOREIGN KEY (output_id) REFERENCES public.outputs(id) ON DELETE CASCADE,
    CONSTRAINT output_tasks_task_id_fkey
        FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS output_tasks_task_id_idx
    ON public.output_tasks (task_id);

ALTER TABLE public.posts
    ADD COLUMN IF NOT EXISTS output_id BIGINT;

ALTER TABLE public.posts
    DROP CONSTRAINT IF EXISTS posts_output_id_fkey;

ALTER TABLE public.posts
    ADD CONSTRAINT posts_output_id_fkey
        FOREIGN KEY (output_id) REFERENCES public.outputs(id) ON DELETE SET NULL;

CREATE UNIQUE INDEX IF NOT EXISTS posts_output_id_key
    ON public.posts (output_id)
    WHERE output_id IS NOT NULL;

COMMIT;
