BEGIN;

-- Bootstrap the legacy schema shape expected by V20260324 when the target
-- database starts completely empty. Existing environments with tables already
-- present skip this migration because Flyway baselines them at 20260324.

CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR NOT NULL,
    nickname VARCHAR NOT NULL,
    profile_image_url VARCHAR,
    bio TEXT,
    email VARCHAR,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_username_key UNIQUE (username),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT blogs_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE
);

CREATE TABLE IF NOT EXISTS public.topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    CONSTRAINT topics_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blog_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    title VARCHAR NOT NULL,
    description TEXT NOT NULL,
    content TEXT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT posts_blog_id_fkey
        FOREIGN KEY (blog_id) REFERENCES public.blogs(id) DEFERRABLE,
    CONSTRAINT posts_author_id_fkey
        FOREIGN KEY (author_id) REFERENCES public.users(id) DEFERRABLE
);

CREATE TABLE IF NOT EXISTS public.post_topics (
    post_id BIGINT NOT NULL,
    topic_id BIGINT NOT NULL,
    PRIMARY KEY (post_id, topic_id),
    CONSTRAINT post_topics_post_id_fkey
        FOREIGN KEY (post_id) REFERENCES public.posts(id) DEFERRABLE,
    CONSTRAINT post_topics_topic_id_fkey
        FOREIGN KEY (topic_id) REFERENCES public.topics(id) DEFERRABLE
);

CREATE TABLE IF NOT EXISTS public.post_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT post_likes_post_id_user_id_key UNIQUE (post_id, user_id),
    CONSTRAINT post_likes_post_id_fkey
        FOREIGN KEY (post_id) REFERENCES public.posts(id) DEFERRABLE,
    CONSTRAINT post_likes_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE
);

CREATE TABLE IF NOT EXISTS public.contributors (
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (post_id, user_id),
    CONSTRAINT contributors_post_id_fkey
        FOREIGN KEY (post_id) REFERENCES public.posts(id) DEFERRABLE,
    CONSTRAINT contributors_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE
);

CREATE TABLE IF NOT EXISTS public.oauth_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR NOT NULL,
    provider_user_id VARCHAR NOT NULL,
    CONSTRAINT oauth_accounts_provider_provider_user_id_key
        UNIQUE (provider, provider_user_id),
    CONSTRAINT oauth_accounts_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE
);

CREATE TABLE IF NOT EXISTS public.suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR NOT NULL,
    post_base_version BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT suggestions_post_id_fkey
        FOREIGN KEY (post_id) REFERENCES public.posts(id) DEFERRABLE,
    CONSTRAINT suggestions_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE
);

CREATE TABLE IF NOT EXISTS public.discussions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suggestion_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT discussions_suggestion_id_fkey
        FOREIGN KEY (suggestion_id) REFERENCES public.suggestions(id) DEFERRABLE,
    CONSTRAINT discussions_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE
);

CREATE TABLE IF NOT EXISTS public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT comments_post_id_fkey
        FOREIGN KEY (post_id) REFERENCES public.posts(id) DEFERRABLE,
    CONSTRAINT comments_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE
);

CREATE TABLE IF NOT EXISTS public.follows (
    following_user_id BIGINT NOT NULL,
    followed_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (following_user_id, followed_user_id),
    CONSTRAINT follows_following_user_id_fkey
        FOREIGN KEY (following_user_id) REFERENCES public.users(id) DEFERRABLE,
    CONSTRAINT follows_followed_user_id_fkey
        FOREIGN KEY (followed_user_id) REFERENCES public.users(id) DEFERRABLE
);

COMMIT;
