BEGIN;

CREATE TABLE public.cli_refresh_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_rotated_at TIMESTAMP,
    CONSTRAINT cli_refresh_sessions_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX cli_refresh_sessions_token_hash_key
    ON public.cli_refresh_sessions (token_hash);

CREATE INDEX cli_refresh_sessions_user_id_idx
    ON public.cli_refresh_sessions (user_id);

CREATE INDEX cli_refresh_sessions_expires_at_idx
    ON public.cli_refresh_sessions (expires_at);

COMMIT;
