CREATE TABLE IF NOT EXISTS public.media_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    post_id BIGINT,
    purpose VARCHAR(50) NOT NULL,
    bucket VARCHAR(255) NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    uploaded_at TIMESTAMP,
    attached_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT media_assets_owner_user_id_fkey
        FOREIGN KEY (owner_user_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT media_assets_post_id_fkey
        FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE SET NULL,
    CONSTRAINT media_assets_object_key_key UNIQUE (object_key),
    CONSTRAINT media_assets_size_bytes_non_negative
        CHECK (size_bytes >= 0)
);

CREATE INDEX IF NOT EXISTS media_assets_owner_user_id_idx
    ON public.media_assets (owner_user_id);

CREATE INDEX IF NOT EXISTS media_assets_post_id_idx
    ON public.media_assets (post_id);

CREATE INDEX IF NOT EXISTS media_assets_status_created_at_idx
    ON public.media_assets (status, created_at);
