BEGIN;

CREATE TABLE IF NOT EXISTS public.task_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_task_id BIGINT NOT NULL,
    to_task_id BIGINT NOT NULL,
    relation VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT task_links_from_task_id_fkey
        FOREIGN KEY (from_task_id) REFERENCES public.tasks(id) ON DELETE CASCADE,
    CONSTRAINT task_links_to_task_id_fkey
        FOREIGN KEY (to_task_id) REFERENCES public.tasks(id) ON DELETE CASCADE,
    CONSTRAINT task_links_no_self_link
        CHECK (from_task_id <> to_task_id),
    CONSTRAINT task_links_relation_check
        CHECK (relation IN ('PRECEDES', 'BLOCKS', 'RELATES_TO')),
    CONSTRAINT task_links_from_to_relation_key
        UNIQUE (from_task_id, to_task_id, relation)
);

CREATE INDEX IF NOT EXISTS task_links_from_task_id_idx
    ON public.task_links (from_task_id);

CREATE INDEX IF NOT EXISTS task_links_to_task_id_idx
    ON public.task_links (to_task_id);

COMMIT;
