BEGIN;

CREATE TABLE public.working_briefs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    task_id BIGINT,
    title VARCHAR(255) NOT NULL,
    prose TEXT NOT NULL,
    branch VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT working_briefs_workspace_id_fkey
        FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE,
    CONSTRAINT working_briefs_author_id_fkey
        FOREIGN KEY (author_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT working_briefs_task_id_fkey
        FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX working_briefs_workspace_id_key
    ON public.working_briefs (workspace_id);

CREATE INDEX working_briefs_task_id_idx
    ON public.working_briefs (task_id);

COMMIT;
