CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL,
    actor_id BIGINT,
    source_event_id UUID NOT NULL,
    type VARCHAR(100) NOT NULL,
    target_domain VARCHAR(100) NOT NULL,
    target_id VARCHAR(255) NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT notifications_recipient_id_fkey
        FOREIGN KEY (recipient_id) REFERENCES public.users(id),
    CONSTRAINT notifications_actor_id_fkey
        FOREIGN KEY (actor_id) REFERENCES public.users(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS notifications_recipient_source_event_key
    ON public.notifications (recipient_id, source_event_id);

CREATE INDEX IF NOT EXISTS notifications_recipient_created_at_idx
    ON public.notifications (recipient_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS notifications_recipient_unread_idx
    ON public.notifications (recipient_id, created_at DESC)
    WHERE read_at IS NULL;
