CREATE TABLE IF NOT EXISTS public.post_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_post_id BIGINT NOT NULL,
    target_post_id BIGINT NOT NULL,
    label VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT post_links_source_post_id_fkey
        FOREIGN KEY (source_post_id) REFERENCES public.posts(id) ON DELETE CASCADE,
    CONSTRAINT post_links_target_post_id_fkey
        FOREIGN KEY (target_post_id) REFERENCES public.posts(id) ON DELETE CASCADE,
    CONSTRAINT post_links_no_self_link
        CHECK (source_post_id <> target_post_id)
);

ALTER TABLE public.post_links
    ADD COLUMN IF NOT EXISTS label VARCHAR(255);

UPDATE public.post_links
SET label = ''
WHERE label IS NULL;

ALTER TABLE public.post_links
    ALTER COLUMN label SET NOT NULL;

ALTER TABLE public.post_links
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS post_links_source_target_label_key
    ON public.post_links (source_post_id, target_post_id, label);

CREATE INDEX IF NOT EXISTS post_links_source_post_id_idx
    ON public.post_links (source_post_id);

CREATE INDEX IF NOT EXISTS post_links_target_post_id_idx
    ON public.post_links (target_post_id);
