BEGIN;

CREATE TABLE public.workspace_agent_guides (
    workspace_id BIGINT PRIMARY KEY,
    content TEXT NOT NULL,
    revision BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT workspace_agent_guides_workspace_id_fkey
        FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE,
    CONSTRAINT workspace_agent_guides_content_length_check
        CHECK (char_length(content) BETWEEN 1 AND 20000),
    CONSTRAINT workspace_agent_guides_revision_check
        CHECK (revision > 0)
);

INSERT INTO public.workspace_agent_guides (workspace_id, content)
SELECT
    id,
    $guide$# Workspace Agent Guide

## Workspace purpose

Use this section to describe what belongs in this workspace and what outcomes matter.

## What is worth recording

- Important technical or product decisions and their rationale
- Relevant problems, root causes, and verified fixes
- Reusable knowledge that will help future work
- Follow-up work that should remain visible after the current session
- Coherent deliverables assembled from completed work

## Choosing a document type

### Task

Use a Task for actionable work that still needs to be started, tracked, or completed. A Task should have a concrete goal and a meaningful completion state.

### Log

Use a Log to preserve an event or knowledge produced during work:

- ISSUE: a relevant problem was discovered
- FIX: a problem's cause and resolution were identified
- DECISION: a meaningful choice and its rationale should be preserved
- NOTE: reusable context does not fit another Log kind

Link a Log to the Task that produced it when applicable.

### Output

Use an Output for a coherent draft that synthesizes one or more Tasks and Logs into a result intended for review, sharing, or later publishing.

## When multiple types apply

- Use a Task as the work container.
- Add important findings and decisions as linked Logs.
- Create an Output only when the accumulated work needs to become a separate deliverable.
- Prefer updating or linking existing documents over creating duplicates.

## Do not record

- Routine file changes or command output
- Temporary errors with no lasting value
- Information already captured in OpenLog
- Raw conversation transcripts
- Secrets, credentials, or personal information
$guide$
FROM public.workspaces
ON CONFLICT (workspace_id) DO NOTHING;

CREATE TABLE public.workspace_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    workspace_id BIGINT NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    repository_full_name VARCHAR(255),
    repository_key VARCHAR(255),
    capture_mode VARCHAR(32) NOT NULL DEFAULT 'ASK',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT workspace_projects_owner_id_fkey
        FOREIGN KEY (owner_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT workspace_projects_workspace_id_fkey
        FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE,
    CONSTRAINT workspace_projects_capture_mode_check
        CHECK (capture_mode IN ('AUTO', 'ASK', 'EXPLICIT')),
    CONSTRAINT workspace_projects_repository_pair_check
        CHECK (
            (repository_full_name IS NULL AND repository_key IS NULL)
            OR (repository_full_name IS NOT NULL AND repository_key IS NOT NULL)
        )
);

CREATE INDEX workspace_projects_workspace_id_idx
    ON public.workspace_projects (workspace_id);

CREATE INDEX workspace_projects_owner_id_idx
    ON public.workspace_projects (owner_id);

CREATE UNIQUE INDEX workspace_projects_owner_repository_key
    ON public.workspace_projects (owner_id, repository_key)
    WHERE repository_key IS NOT NULL;

INSERT INTO public.workspace_projects (
    owner_id,
    workspace_id,
    display_name,
    repository_full_name,
    repository_key,
    capture_mode
)
SELECT DISTINCT ON (owner_id, lower(trim(repo_full_name)))
    owner_id,
    id,
    trim(repo_full_name),
    trim(repo_full_name),
    lower(trim(repo_full_name)),
    'ASK'
FROM public.workspaces
WHERE repo_full_name IS NOT NULL
  AND trim(repo_full_name) <> ''
ORDER BY owner_id, lower(trim(repo_full_name)), id
ON CONFLICT DO NOTHING;

ALTER TABLE public.workspaces
    DROP COLUMN repo_full_name;

COMMIT;
