BEGIN;

CREATE TABLE public.memories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    task_id BIGINT,
    origin_log_id BIGINT,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT memories_workspace_id_fkey
        FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE,
    CONSTRAINT memories_author_id_fkey
        FOREIGN KEY (author_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT memories_task_id_fkey
        FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE SET NULL,
    CONSTRAINT memories_origin_log_id_fkey
        FOREIGN KEY (origin_log_id) REFERENCES public.logs(id) ON DELETE SET NULL
);

CREATE INDEX memories_workspace_updated_at_idx
    ON public.memories (workspace_id, updated_at DESC, id DESC);

CREATE INDEX memories_task_id_idx
    ON public.memories (task_id);

CREATE UNIQUE INDEX memories_origin_log_id_key
    ON public.memories (origin_log_id)
    WHERE origin_log_id IS NOT NULL;

COMMIT;
