BEGIN;

CREATE TABLE IF NOT EXISTS public.cross_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    from_task_id BIGINT,
    from_log_id BIGINT,
    from_output_id BIGINT,
    from_memory_id BIGINT,
    to_task_id BIGINT,
    to_log_id BIGINT,
    to_output_id BIGINT,
    to_memory_id BIGINT,
    relation VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT cross_links_workspace_id_fkey
        FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE,
    CONSTRAINT cross_links_from_task_id_fkey
        FOREIGN KEY (from_task_id) REFERENCES public.tasks(id) ON DELETE CASCADE,
    CONSTRAINT cross_links_from_log_id_fkey
        FOREIGN KEY (from_log_id) REFERENCES public.logs(id) ON DELETE CASCADE,
    CONSTRAINT cross_links_from_output_id_fkey
        FOREIGN KEY (from_output_id) REFERENCES public.outputs(id) ON DELETE CASCADE,
    CONSTRAINT cross_links_from_memory_id_fkey
        FOREIGN KEY (from_memory_id) REFERENCES public.memories(id) ON DELETE CASCADE,
    CONSTRAINT cross_links_to_task_id_fkey
        FOREIGN KEY (to_task_id) REFERENCES public.tasks(id) ON DELETE CASCADE,
    CONSTRAINT cross_links_to_log_id_fkey
        FOREIGN KEY (to_log_id) REFERENCES public.logs(id) ON DELETE CASCADE,
    CONSTRAINT cross_links_to_output_id_fkey
        FOREIGN KEY (to_output_id) REFERENCES public.outputs(id) ON DELETE CASCADE,
    CONSTRAINT cross_links_to_memory_id_fkey
        FOREIGN KEY (to_memory_id) REFERENCES public.memories(id) ON DELETE CASCADE,
    CONSTRAINT cross_links_one_from_node
        CHECK (num_nonnulls(from_task_id, from_log_id, from_output_id, from_memory_id) = 1),
    CONSTRAINT cross_links_one_to_node
        CHECK (num_nonnulls(to_task_id, to_log_id, to_output_id, to_memory_id) = 1),
    CONSTRAINT cross_links_different_node_types
        CHECK (
            (from_task_id IS NULL OR to_task_id IS NULL)
            AND (from_log_id IS NULL OR to_log_id IS NULL)
            AND (from_output_id IS NULL OR to_output_id IS NULL)
            AND (from_memory_id IS NULL OR to_memory_id IS NULL)
        ),
    CONSTRAINT cross_links_relation_check
        CHECK (relation IN ('RELATES_TO', 'REFERENCES', 'SUPPORTS', 'DERIVED_FROM'))
);

CREATE UNIQUE INDEX IF NOT EXISTS cross_links_unique_edge_idx
    ON public.cross_links (
        workspace_id,
        COALESCE(from_task_id, 0),
        COALESCE(from_log_id, 0),
        COALESCE(from_output_id, 0),
        COALESCE(from_memory_id, 0),
        COALESCE(to_task_id, 0),
        COALESCE(to_log_id, 0),
        COALESCE(to_output_id, 0),
        COALESCE(to_memory_id, 0),
        relation
    );

CREATE INDEX IF NOT EXISTS cross_links_workspace_id_idx ON public.cross_links (workspace_id);
CREATE INDEX IF NOT EXISTS cross_links_from_task_id_idx ON public.cross_links (from_task_id);
CREATE INDEX IF NOT EXISTS cross_links_from_log_id_idx ON public.cross_links (from_log_id);
CREATE INDEX IF NOT EXISTS cross_links_from_output_id_idx ON public.cross_links (from_output_id);
CREATE INDEX IF NOT EXISTS cross_links_from_memory_id_idx ON public.cross_links (from_memory_id);
CREATE INDEX IF NOT EXISTS cross_links_to_task_id_idx ON public.cross_links (to_task_id);
CREATE INDEX IF NOT EXISTS cross_links_to_log_id_idx ON public.cross_links (to_log_id);
CREATE INDEX IF NOT EXISTS cross_links_to_output_id_idx ON public.cross_links (to_output_id);
CREATE INDEX IF NOT EXISTS cross_links_to_memory_id_idx ON public.cross_links (to_memory_id);

COMMIT;
